export const ERROR_CODE = Object.freeze({
  UNKNOWN: 'UNKNOWN',

  CONFIGURATION: 'CONFIGURATION_ERROR',

  VALIDATION: 'VALIDATION_ERROR',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',

  CONFLICT: 'CONFLICT',

  PROVIDER: 'PROVIDER_ERROR',

  STORAGE: 'STORAGE_ERROR',

  WORKFLOW: 'WORKFLOW_ERROR',

  INTERNAL: 'INTERNAL_ERROR'
});