// FILE: src/core/constants/workflow.js

export const WORKFLOW_STATE = Object.freeze({
  IDLE: 'IDLE',
  MENU: 'MENU',
  CANCELLED: 'CANCELLED',

  // 🚀 STATE MUTLAK WORKFLOW HYBRID EDITOR
  HYBRID_WAITING_TITLE: 'HYBRID_WAITING_TITLE',
  HYBRID_WAITING_BODY: 'HYBRID_WAITING_BODY',
  HYBRID_ANALYZING: 'HYBRID_ANALYZING',
  HYBRID_WAITING_IMAGE: 'HYBRID_WAITING_IMAGE',
  HYBRID_PUBLISHING: 'HYBRID_PUBLISHING',
  FINISHED: 'FINISHED'
});