// FILE: src/core/constants/workflow.js

export const WORKFLOW_STATE = Object.freeze({
  IDLE: 'IDLE',
  MENU: 'MENU',

  WAITING_ARTICLE: 'WAITING_ARTICLE',
  WAITING_ANGLE: 'WAITING_ANGLE',
  OCR_PROCESSING: 'OCR_PROCESSING',
  EDITORIAL_PROCESSING: 'EDITORIAL_PROCESSING',
  WAITING_REVIEW: 'WAITING_REVIEW',
  WAITING_MANUAL_EDIT: 'WAITING_MANUAL_EDIT',
  WAITING_FEATURED_IMAGE: 'WAITING_FEATURED_IMAGE',
  PUBLISHING: 'PUBLISHING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',

  // 🚀 STATE KHUSUS UNTUK WORKFLOW HYBRID EDITOR
  HYBRID_WAITING_TITLE: 'HYBRID_WAITING_TITLE',
  HYBRID_WAITING_BODY: 'HYBRID_WAITING_BODY',
  HYBRID_ANALYZING: 'HYBRID_ANALYZING',
  HYBRID_WAITING_IMAGE: 'HYBRID_WAITING_IMAGE',
  HYBRID_PUBLISHING: 'HYBRID_PUBLISHING',
  FINISHED: 'FINISHED',
});
