export const WORKFLOW_STATE = Object.freeze({
  RECEIVED: 'RECEIVED',
  OCR_PENDING: 'OCR_PENDING',
  OCR_COMPLETED: 'OCR_COMPLETED',
  REWRITE_PENDING: 'REWRITE_PENDING',
  REWRITE_COMPLETED: 'REWRITE_COMPLETED',
  SEO_PENDING: 'SEO_PENDING',
  SEO_COMPLETED: 'SEO_COMPLETED',
  EDITORIAL_PENDING: 'EDITORIAL_PENDING',
  APPROVED: 'APPROVED',
  PUBLISH_PENDING: 'PUBLISH_PENDING',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED'
});