// FILE: src/infrastructure/providers/wordpress/category-map.js

/**
 * PETA KATEGORI RESMI WEBSITE GESAHAN NUSANTARA
 *
 * Dipetakan secara presisi berdasarkan ID taksonomi kategori riil di WordPress.
 * Mencegah duplikasi data dan menjamin postingan masuk ke kanal yang tepat.
 */
export const WORDPRESS_CATEGORY_MAP = Object.freeze({
  // DEFAULT (non kategory)
  BERITA: 1,

  // SEKTOR NASIONAL
  NASIONAL: 2,
  POLRI: 385,
  TNI: 384,
  PEMERINTAHAN: 382,
  KEBIJAKAN: 386,
  INFRASTRUKTUR: 387,
  'DPR NASIONAL': 383,

  // SEKTOR POLITIK
  POLITIK: 69,
  PEMERINTAH: 445,
  PEMILU: 443,
  PILKADA: 442,
  'PARTAI POLITIK': 446,
  'DPR POLITIK': 444,

  // SEKTOR HUKUM & PERISTIWA (HARD NEWS)
  HUKUM: 435,
  KEPOLISIAN: 439,
  KRIMINAL: 436,
  NARKOBA: 441,
  KORUPSI: 440,
  KEJAKSAAN: 438,
  PENGADILAN: 437,
  'POLRES PAGARALAM': 488,

  // SEKTOR EKONOMI & BISNIS
  EKONOMI: 447,
  BISNIS: 54,
  'BISNIS EKONOMI': 448,
  INVESTASI: 450,
  KEUANGAN: 451,
  PERBANKAN: 452,
  ENERGI: 453,
  UMKM: 449,

  // SEKTOR DAERAH (REGIONAL)
  DAERAH: 388,
  SUMATERA: 389,
  JAWA: 400,
  KALIMANTAN: 407,
  SULAWESI: 413,
  'BALI & NUSA TENGGARA': 420,
  MALUKU: 424,
  PAPUA: 433,
  SUMSEL: 482,

  // SEKTOR INTERNASIONAL
  INTERNASIONAL: 434,

  // SEKTOR LIFESTYLE & HIBURAN (SOFT NEWS)
  LIFESTYLE: 464,
  KULINER: 466,
  FASHION: 467,
  TRAVEL: 465,
  KOMUNITAS: 469,
  'OTOMOTIF LIFESTYLE': 468,

  // SEKTOR MINAT KHUSUS
  OLAHRAGA: 70,
  OTOMOTIF: 71,
});
